### ISSUE TITLE
Ensure UTF-8

### ISSUE THREAD

**Issue by gbinal** [18F/autoapi#13]
Per the 18F API Standards - https://github.com/18F/api-standards#use-utf-8

**Comment by catherinedevlin** [comment]
Example problem:

`2016-04-25T17:36:01.01-0400 [App/0]      ERR INFO:tasks:Importing raw/pass-list tk 8-28-15.csv to table pass-list tk 8-28-15
2016-04-25T17:36:01.01-0400 [App/0]      ERR INFO:utils:Dropping table pass-list tk 8-28-15
2016-04-25T17:36:01.05-0400 [App/0]      ERR ERROR:aws:'utf-8' codec can't decode byte 0xe5 in position 50: invalid continuation byte
2016-04-25T17:36:01.05-0400 [App/0]      ERR Traceback (most recent call last):
2016-04-25T17:36:01.05-0400 [App/0]      ERR   File "/home/vcap/app/aws.py", line 149, in fetch_key
2016-04-25T17:36:01.05-0400 [App/0]      ERR     tasks.apify(filename)
2016-04-25T17:36:01.05-0400 [App/0]      ERR   File "/app/.heroku/python/lib/python3.4/site-packages/invoke/tasks.py", line 113, in __call__
2016-04-25T17:36:01.05-0400 [App/0]      ERR     result = self.body(*args, **kwargs)
2016-04-25T17:36:01.05-0400 [App/0]      ERR   File "/home/vcap/app/tasks.py", line 30, in apify
2016-04-25T17:36:01.05-0400 [App/0]      ERR     utils.load_table(filename, tablename)
2016-04-25T17:36:01.05-0400 [App/0]      ERR   File "/home/vcap/app/utils.py", line 73, in load_table
2016-04-25T17:36:01.05-0400 [App/0]      ERR     for idx, chunk in enumerate(chunks):
2016-04-25T17:36:01.05-0400 [App/0]      ERR   File "/app/.heroku/python/lib/python3.4/site-packages/pandas/io/parsers.py", line 743, in __next__
2016-04-25T17:36:01.05-0400 [App/0]      ERR     return self.get_chunk()
2016-04-25T17:36:01.05-0400 [App/0]      ERR   File "/app/.heroku/python/lib/python3.4/site-packages/pandas/io/parsers.py", line 784, in get_chunk
2016-04-25T17:36:01.05-0400 [App/0]      ERR     return self.read(nrows=size)
2016-04-25T17:36:01.05-0400 [App/0]      ERR   File "/app/.heroku/python/lib/python3.4/site-packages/pandas/io/parsers.py", line 763, in read
2016-04-25T17:36:01.05-0400 [App/0]      ERR     ret = self._engine.read(nrows)
2016-04-25T17:36:01.05-0400 [App/0]      ERR   File "/app/.heroku/python/lib/python3.4/site-packages/pandas/io/parsers.py", line 1213, in read
2016-04-25T17:36:01.05-0400 [App/0]      ERR     data = self._reader.read(nrows)
2016-04-25T17:36:01.05-0400 [App/0]      ERR   File "pandas/parser.pyx", line 766, in pandas.parser.TextReader.read (pandas/parser.c:7988)
2016-04-25T17:36:01.05-0400 [App/0]      ERR   File "pandas/parser.pyx", line 800, in pandas.parser.TextReader._read_low_memory (pandas/parser.c:8444)
2016-04-25T17:36:01.05-0400 [App/0]      ERR   File "pandas/parser.pyx", line 865, in pandas.parser.TextReader._read_rows (pandas/parser.c:9261)
2016-04-25T17:36:01.05-0400 [App/0]      ERR   File "pandas/parser.pyx", line 972, in pandas.parser.TextReader._convert_column_data (pandas/parser.c:10654)
2016-04-25T17:36:01.05-0400 [App/0]      ERR   File "pandas/parser.pyx", line 1019, in pandas.parser.TextReader._convert_tokens (pandas/parser.c:11333)
2016-04-25T17:36:01.05-0400 [App/0]      ERR   File "pandas/parser.pyx", line 1118, in pandas.parser.TextReader._convert_with_dtype (pandas/parser.c:12976)
2016-04-25T17:36:01.05-0400 [App/0]      ERR   File "pandas/parser.pyx", line 1138, in pandas.parser.TextReader._string_convert (pandas/parser.c:13222)
2016-04-25T17:36:01.05-0400 [App/0]      ERR   File "pandas/parser.pyx", line 1370, in pandas.parser._string_box_utf8 (pandas/parser.c:18598)
2016-04-25T17:36:01.05-0400 [App/0]      ERR UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 50: invalid continuation byte`
